rok_urodzenia = int(input("Podaj rok urodzenia solenizanta/solenizantki:"))
imie_solenizant = input("Podaj imię solenizanta/solenizantki:")
imie_nadawca = input("Podaj swoje imię:")
wiadomosc = input("Podaj wiadomość, którą ma otrzymać solenizant/solenizantka:")
wiek = int(2024 - rok_urodzenia)
print(f"{imie_solenizant}, wszystkiego najlepszego z okazji {wiek} urodzin! ")
print("")
print(wiadomosc)
print("")
print(imie_nadawca)